Pushing data to database in chunks. Give names of the tables where you want the data to be pushed. If you want a table where duplicates arent allowed pass unique = True (In this case make sure the name of the table isnt taken)

In [1]:
from Modules.full_feature_matrix import create_full_feature_and_target_matrix
create_full_feature_and_target_matrix(printProgress=True, pushToDatabase = True, chunksize = 1000, featuresTableName = 'featurestest2', targetTableName = 'targettest2', combinedTableName='Preprocessed4', unique = True)

If you just want the data but dont want to push it to the database just go like this in below.(Push to database is on False on default)

In [1]:
from Modules.full_feature_matrix import create_full_feature_and_target_matrix
df_features, df_target=create_full_feature_and_target_matrix(printProgress = True)

2021-11-18 13:01:14,833| ERROR   | Password is required for key /home/jovyan/.ssh/id_ed25519

In [2]:
df_features

,peelFile,m_uWidth,m_uLength,m_dThickness,B1MoistureAvg,B1TemperatureAvg,B1DensityAvg,B1KnotWidthSum,B1KnotCount,B1DecayWidthSum,...,B8AllOtherDefectCount,B9MoistureAvg,B9TemperatureAvg,B9DensityAvg,B9KnotWidthSum,B9KnotCount,B9DecayWidthSum,B9DecayCount,B9AllOtherDefectWidthSum,B9AllOtherDefectCount
0,20210505123334_85.datx,1750.23265,1599.76152,1.56,117.582404,33.010073,1004.081748,125.39330,11,26.9537,...,0,125.324911,33.845573,1028.419309,157.62055,19,39.25865,2,16.99255,2
1,20210505135613_40.datx,1750.23265,1603.25064,1.56,92.388576,30.617250,NaN,0.00000,0,0.0000,...,0,98.377927,27.752846,1345.817186,26.36775,4,0.00000,0,0.00000,0
2,20210505150804_9.datx,1750.23265,1599.18000,1.56,101.473622,34.158417,961.639685,0.00000,0,0.0000,...,0,102.674582,34.486729,NaN,12.89090,1,0.00000,0,7.03140,1
3,20210505125941_29.datx,1750.23265,1601.50608,1.56,88.373384,35.438937,827.377599,21.68015,2,0.0000,...,0,92.668053,35.587054,NaN,49.21980,3,0.00000,0,16.40660,4
4,20210505123435_23.datx,1750.23265,1600.34304,1.56,120.877675,35.854021,956.372132,22.26610,3,0.0000,...,1,115.523224,35.723542,960.543745,15.82065,3,0.00000,0,450.00960,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,20210505125748_61.datx,1750.23265,1600.92456,1.56,93.128344,27.922545,865.955931,65.04045,10,0.0000,...,0,96.907931,27.696730,884.802702,87.30655,9,68.55615,2,0.00000,0
142,20210505145008_84.datx,1750.23265,1601.50608,1.56,95.698248,36.123000,952.906867,56.25120,7,0.0000,...,0,99.479994,35.438239,947.239349,67.97020,9,0.00000,0,0.00000,0
143,20210505125913_15.datx,1614.87820,1596.85392,1.56,89.492242,35.878303,853.189124,43.94625,7,0.0000,...,0,87.113549,35.705853,NaN,60.93880,11,0.00000,0,0.00000,0
144,20210505124918_24.datx,1750.23265,1601.50608,1.56,89.761967,35.592812,912.424399,96.68175,11,0.0000,...,0,90.379964,34.953594,NaN,79.10325,9,94.92390,7,0.00000,0
145,20210505123049_48.datx,1750.23265,1596.85392,1.56,106.229193,33.715803,910.443370,8.20330,1,0.0000,...,0,105.891692,33.997678,907.915775,17.57850,1,0.00000,0,0.00000,0

If you want to see what is inside your database or want to give any query use ssh_connector module.

In [7]:
from Modules.ssh_connector import *

c = Connector('/home/jovyan/work/salasana.env')
data = c.connector(query = "SHOW TABLES;")
data

2021-11-18 13:28:38,698| ERROR   | Password is required for key /home/jovyan/.ssh/id_ed25519

  Tables_in_Projekti
0   PreprocessedData
1      VerifiedPairs

With ssh_connector module you can get data from the database.

In [8]:
data = c.connector(query = "SELECT * FROM PreprocessedData;")
data

2021-11-18 13:28:44,660| ERROR   | Password is required for key /home/jovyan/.ssh/id_ed25519

,index,peelFile,m_uWidth,m_uLength,m_dThickness,B1MoistureAvg,B1TemperatureAvg,B1DensityAvg,B1KnotWidthSum,B1KnotCount,...,B8AllOtherDefectCount,B9MoistureAvg,B9TemperatureAvg,B9DensityAvg,B9KnotWidthSum,B9KnotCount,B9DecayWidthSum,B9DecayCount,B9AllOtherDefectWidthSum,B9AllOtherDefectCount
0,0,20210505123334_85.datx,1750.23265,1599.76152,1.56,117.582404,33.010073,1004.081748,125.39330,11,...,0,125.324911,33.845573,1028.419309,157.62055,19,39.25865,2,16.99255,2
1,1,20210505135613_40.datx,1750.23265,1603.25064,1.56,92.388576,30.617250,NaN,0.00000,0,...,0,98.377927,27.752846,1345.817186,26.36775,4,0.00000,0,0.00000,0
2,2,20210505150804_9.datx,1750.23265,1599.18000,1.56,101.473622,34.158417,961.639685,0.00000,0,...,0,102.674582,34.486729,NaN,12.89090,1,0.00000,0,7.03140,1
3,3,20210505125941_29.datx,1750.23265,1601.50608,1.56,88.373384,35.438937,827.377599,21.68015,2,...,0,92.668053,35.587054,NaN,49.21980,3,0.00000,0,16.40660,4
4,4,20210505123435_23.datx,1750.23265,1600.34304,1.56,120.877675,35.854021,956.372132,22.26610,3,...,1,115.523224,35.723542,960.543745,15.82065,3,0.00000,0,450.00960,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,141,20210505125748_61.datx,1750.23265,1600.92456,1.56,93.128344,27.922545,865.955931,65.04045,10,...,0,96.907931,27.696730,884.802702,87.30655,9,68.55615,2,0.00000,0
142,142,20210505145008_84.datx,1750.23265,1601.50608,1.56,95.698248,36.123000,952.906867,56.25120,7,...,0,99.479994,35.438239,947.239349,67.97020,9,0.00000,0,0.00000,0
143,143,20210505125913_15.datx,1614.87820,1596.85392,1.56,89.492242,35.878303,853.189124,43.94625,7,...,0,87.113549,35.705853,NaN,60.93880,11,0.00000,0,0.00000,0
144,144,20210505124918_24.datx,1750.23265,1601.50608,1.56,89.761967,35.592812,912.424399,96.68175,11,...,0,90.379964,34.953594,NaN,79.10325,9,94.92390,7,0.00000,0
145,145,20210505123049_48.datx,1750.23265,1596.85392,1.56,106.229193,33.715803,910.443370,8.20330,1,...,0,105.891692,33.997678,907.915775,17.57850,1,0.00000,0,0.00000,0